name: keelung
version: 0.26.1
github: "btq-ag/keelung"
license: Apache-2.0
author: "BTQ AG"
maintainer: "BTQ AG"
copyright: "2022-2023 BTQ AG"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: DSL for creating zero-knowledge proofs
category: Cryptography

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/btq-ag/keelung#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - cereal
  - containers
  - deepseq
  - directory
  - galois-field
  - groups
  - mtl
  - optparse-applicative
  - process
  - random
  - semirings
  - QuickCheck
  - vector
  - wl-pprint-text
  - aeson
  - attoparsec

library:
  source-dirs: src
default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Werror=incomplete-patterns
  - -fno-warn-orphans

tests:
  keelung-test:
    main: Main.hs
    source-dirs:
      - test/
      - src/
    dependencies:
      - keelung
      # - keelung-examples
      - hspec
      - hspec-expectations-lifted
      - HUnit
      - QuickCheck
      - quickcheck-transformer

    ghc-options:
      - -Wall
      - -Werror=incomplete-patterns
      - -fno-warn-orphans
